import { Controller, Get, NotFoundException, Param, Patch, Query, UseGuards } from '@nestjs/common';
import { JwtAuthGuard } from '../guards/jwt-auth.guard';
import { PermissionGuard } from '../guards/permission.guard';
import { RequirePermission } from '../decorators/require-permission.decorator';
import { CurrentUser } from '../decorators/current-user.decorator';
import { JWTPayload } from '../../../application/ports/jwt.port';
import {
  ListPurchaseOrderDraftsUseCase,
  DecidePurchaseOrderDraftUseCase,
} from '../../../application/use-cases/purchase-orders/purchase-orders.use-cases';

/**
 * Purchase-order drafts generated by the inventory agent. OWNER/ADMIN review
 * and approve/reject them. Reuses inventory permissions.
 */
@Controller('purchase-orders')
@UseGuards(JwtAuthGuard, PermissionGuard)
export class PurchaseOrdersController {
  constructor(
    private readonly listDrafts: ListPurchaseOrderDraftsUseCase,
    private readonly decide: DecidePurchaseOrderDraftUseCase,
  ) {}

  @Get()
  @RequirePermission('inventory:READ')
  async list(
    @CurrentUser() user: JWTPayload,
    @Query('page') page?: string,
    @Query('pageSize') pageSize?: string,
  ) {
    return this.listDrafts.execute(user.tenantId, {
      page: page ? Number(page) : 1,
      pageSize: pageSize ? Number(pageSize) : 20,
    });
  }

  @Patch(':id/approve')
  @RequirePermission('inventory:UPDATE')
  async approve(@CurrentUser() user: JWTPayload, @Param('id') id: string) {
    const updated = await this.decide.execute(id, user.tenantId, 'APPROVED', user.sub);
    if (!updated) throw new NotFoundException('Purchase order draft not found');
    return updated;
  }

  @Patch(':id/reject')
  @RequirePermission('inventory:UPDATE')
  async reject(@CurrentUser() user: JWTPayload, @Param('id') id: string) {
    const updated = await this.decide.execute(id, user.tenantId, 'REJECTED', user.sub);
    if (!updated) throw new NotFoundException('Purchase order draft not found');
    return updated;
  }
}
