import {
  Controller,
  Get,
  NotFoundException,
  Param,
  Query,
  UnprocessableEntityException,
  UseGuards,
} from '@nestjs/common';
import { JwtAuthGuard } from '../guards/jwt-auth.guard';
import { PermissionGuard } from '../guards/permission.guard';
import { RequirePermission } from '../decorators/require-permission.decorator';
import { CurrentUser } from '../decorators/current-user.decorator';
import { JWTPayload } from '../../../application/ports/jwt.port';
import {
  ListReportsUseCase,
  GetReportDownloadUrlUseCase,
} from '../../../application/use-cases/agents/agents.use-cases';

/**
 * Web-facing reports surface (OWNER/ADMIN). Lists reports generated by the
 * agents service and issues short-lived R2 download URLs.
 */
@Controller('reports')
@UseGuards(JwtAuthGuard, PermissionGuard)
export class ReportsController {
  constructor(
    private readonly listReports: ListReportsUseCase,
    private readonly downloadUrl: GetReportDownloadUrlUseCase,
  ) {}

  @Get()
  @RequirePermission('reports:READ')
  async list(
    @CurrentUser() user: JWTPayload,
    @Query('page') page?: string,
    @Query('pageSize') pageSize?: string,
  ) {
    return this.listReports.execute(user.tenantId, {
      page: page ? Number(page) : 1,
      pageSize: pageSize ? Number(pageSize) : 20,
    });
  }

  @Get(':id/download')
  @RequirePermission('reports:READ')
  async download(@CurrentUser() user: JWTPayload, @Param('id') id: string) {
    const result = await this.downloadUrl.execute(id, user.tenantId);
    if (result.status === 'NOT_FOUND') {
      throw new NotFoundException('Report not found');
    }
    if (result.status === 'NOT_READY') {
      throw new UnprocessableEntityException(
        `Report is not ready (status: ${result.reportStatus})`,
      );
    }
    return { url: result.url, expiresInSeconds: result.expiresInSeconds };
  }
}
